baseURL = "https://mimium.org"
title = "mimium"

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

[outputs] # add print &rss support
section = ["HTML", "RSS", "print"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"


[[menu.main]]
name = "Community"
weight = 40
url = "https://gitter.im/mimium-dev/community"
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "Smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
title = "mimium"
languageName = "English"
[languages.en.params]
description = "mimium(MInimal Musical medIUM) - a programming language as an infrastructure for sound and music."
# Weight used for sorting.
weight = 1
[languages.ja]
title = "mimium"
languageName = "Japanese"
[languages.ja.params]
time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"
description = "mimium(MInimal Musical medIUM) - a programming language as an infrastructure for sound and music."


[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true

# Everything below this are Site Params

[params]

BookTheme = 'auto'

# First one is picked as the Twitter card image if not set on page.
images = ["img/mimium-sc.png"]
BookLogo = "img/mimium_logo_slant.svg"
BookDateFormat = '2006-01-02'
BookComments = false

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
BookRepo = "https://github.com/mimium-org/mimium-web"
BookCommitPath = 'commit'
BookEditPath = 'edit/master'
[menus]
[[menu.after]]
name = "GitHub"
url = "https://github.com/tomoyanonymous/mimium-rs"
weight = 10
[menu.after.params]
icon_vendor = "fab"
icon = "github"
[[menu.after]]
name = "Twitter(X)"
url = "https://twitter.com/mimium-org"
[menu.after.params]
icon_vendor = "fab"
icon = "twitter"
weight = 20
[[menu.after]]
name = "Chat(Matrix)"
url = "https://matrix.to/#/#mimium:matrix.org"
weight = 30
[menu.after.params]
icon_vendor = "tabler"
icon = "outline/brand-matrix"




[module]
proxy = "direct"
# uncomment line below for temporary local development of module
# replacements = "github.com/google/docsy -> ../../docsy"
[module.hugoVersion]
extended = true
min = "0.130.0"
# [[module.imports]]
# path = "github.com/google/docsy"
# disable = false
[[module.imports]]
path = "github.com/KKKZOZ/hugo-admonitions"
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'
[[module.imports]]
path = 'github.com/tomoyanonymous/hugo-micromorph'
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/font-awesome'
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/tabler'