backend:
  name: github
  repo: mimium-org/mimium-web
  open_authoring: true

publish_mode: editorial_workflow
site_url: https://mimium.org
logo_url: https://raw.githubusercontent.com/mimium-org/mimium/132b8f7037b61a3836a8b9ecc486415994911c22/mimium_logo_slant.svg

media_folder: static/img
public_folder: /img
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files
  # Required - a list of locales to show in the editor UI
  locales: [en, ja]
  default_locale: en

collections:
  - name: "docs"
    label: "Documentation"
    folder: "content/en/docs"
    create: true
    i18n: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "LinkTitle",
          name: "LinkTitle",
          widget: "string",
          required: false,
          i18n: true,
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - {
          label: "Weight",
          name: "weight",
          widget: "number",
          value_type: "int",
          required: false,
          min: 1,
          default: 1,
          i18n: "duplicate",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true,
        }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: true,
          i18n: "duplicate",
        }
      - {
          label: "Hide from Sidebar Menu",
          name: "bookHidden",
          widget: "boolean",
          default: false,
          i18n: "duplicate",
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "Users-Guide"
    label: "Users-Guide"
    folder: "content/en/docs/user_guide"
    create: true
    i18n: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "LinkTitle",
          name: "LinkTitle",
          widget: "string",
          required: false,
          i18n: true,
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - {
          label: "Weight",
          name: "weight",
          widget: "number",
          value_type: "int",
          required: false,
          min: 1,
          default: 1,
          i18n: "duplicate",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true,
        }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: true,
          i18n: "duplicate",
        }
      - {
          label: "Hide from Sidebar Menu",
          name: "BoolHideSection",
          widget: "boolean",
          default: false,
          i18n: "duplicate",
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "Getting-started"
    label: "Getting-started"
    folder: "content/en/docs/getting_started"
    create: true
    i18n: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "LinkTitle",
          name: "LinkTitle",
          widget: "string",
          required: false,
          i18n: true,
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - {
          label: "Weight",
          name: "weight",
          widget: "number",
          value_type: "int",
          required: false,
          min: 1,
          default: 1,
          i18n: "duplicate",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true,
        }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: true,
          i18n: "duplicate",
        }
      - {
          label: "Hide from Sidebar Menu",
          name: "bookHidden",
          widget: "boolean",
          default: false,
          i18n: "duplicate",
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "Developers-Guide"
    label: "Developers-Guide"
    folder: "content/en/docs/developer_guide"
    create: true
    i18n: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "LinkTitle",
          name: "LinkTitle",
          widget: "string",
          required: false,
          i18n: true,
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - {
          label: "Weight",
          name: "weight",
          widget: "number",
          value_type: "int",
          required: false,
          min: 1,
          default: 1,
          i18n: "duplicate",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true,
        }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: true,
          i18n: "duplicate",
        }
      - {
          label: "Hide from Sidebar Menu",
          name: "bookHidden",
          widget: "boolean",
          default: false,
          i18n: "duplicate",
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "Contributing"
    label: "Contributing"
    folder: "content/en/docs/contributing"
    create: true
    i18n: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "LinkTitle",
          name: "LinkTitle",
          widget: "string",
          required: false,
          i18n: true,
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - {
          label: "Weight",
          name: "weight",
          widget: "number",
          value_type: "int",
          required: false,
          min: 1,
          default: 1,
          i18n: "duplicate",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true,
        }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: true,
          i18n: "duplicate",
        }
      - {
          label: "Hide from Sidebar Menu",
          name: "bookHidden",
          widget: "boolean",
          default: false,
          i18n: "duplicate",
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "Blog-news"
    label: "Blog-News"
    folder: "content/en/posts"
    create: true
    i18n: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "LinkTitle",
          name: "LinkTitle",
          widget: "string",
          required: false,
          i18n: true,
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - {
          label: "Weight",
          name: "weight",
          widget: "number",
          value_type: "int",
          required: false,
          min: 1,
          default: 1,
          i18n: "duplicate",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true,
        }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: true,
          i18n: "duplicate",
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
